name: task2-ansible

on:
  workflow_dispatch:
    inputs:
      droplet_ip:
        description: 'IP адреса дроплету'
        required: true

jobs:
  ansible:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task2

    env:
      DROPLET_IP: ${{ github.event.inputs.droplet_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts

      - name: Ansible check (dry-run)
        run: |
          ansible-playbook -i inventory/hosts.yml playbook.yml \
          --private-key /tmp/ssh_key \
          --user root \
          --check

      - name: Ansible apply
        run: |
          ansible-playbook -i inventory/hosts.yml playbook.yml \
          --private-key /tmp/ssh_key \
          --user root
